### PR TITLE
Add Support For Invisible reCAPTCHA

### PR DESCRIPTION
**Pull request by LouiseBC**
Pretty self-explanatory :)

### CODE REVIEW

**Comment by joe-f** [comment]
@appleboy Can we get this approved and merged into a release please?

**Comment by davidvgalbraith** [comment]
+1

**Comment by vlad-grigoryan** [comment]
+1

**Comment by RyanGosden** [comment]
+1

**Comment by appleboy** [comment]
@LouiseBC Thanks. I will release the next version.

**Comment by appleboy** [comment]
bump to `2.3.7` version.

**Comment by RyanGosden** [comment]
Thanks!
You can also closed issue #198

**Pull request merged**
